# Google Sheet IDs for each brand (from shared links).
# Export URL format: https://docs.google.com/spreadsheets/d/{id}/export?format=csv&gid=0
# Sheets must be shared as "Anyone with the link can view" for download to work.

brands:
  - id: enday
    name: Enday
    sheet_id: 1bD7FHj9_qczskyDGWgKGsnK3aL7NnNrhKhutms_QYZU
    link: "https://docs.google.com/spreadsheets/d/1bD7FHj9_qczskyDGWgKGsnK3aL7NnNrhKhutms_QYZU/edit?usp=sharing"

  - id: aurora
    name: Aurora
    sheet_id: 1kY8sVQBeBnP9zmYyAHHFZv3cJqiYmLeuBD1AjLC883Q
    link: "https://docs.google.com/spreadsheets/d/1kY8sVQBeBnP9zmYyAHHFZv3cJqiYmLeuBD1AjLC883Q/edit?usp=sharing"

  - id: bazic
    name: Bazic
    sheet_id: 1B4Y04L4xIdoP306mxtzEu_VMdbqdrTBXQmk_C-klgjw
    link: "https://docs.google.com/spreadsheets/d/1B4Y04L4xIdoP306mxtzEu_VMdbqdrTBXQmk_C-klgjw/edit?usp=sharing"

  - id: bruder
    name: Bruder
    sheet_id: 1c1Qh55EHhsR0Jb6ReMP2w0A3yQXU9tJNh7bV1sQGn1w
    link: "https://docs.google.com/spreadsheets/d/1c1Qh55EHhsR0Jb6ReMP2w0A3yQXU9tJNh7bV1sQGn1w/edit?usp=sharing"

  - id: razor
    name: Razor
    sheet_id: 1Q7ltzpx-fTM4aSOcUk-Fgpvba82k00iTjNF1zhQB27I
    link: "https://docs.google.com/spreadsheets/d/1Q7ltzpx-fTM4aSOcUk-Fgpvba82k00iTjNF1zhQB27I/edit?usp=sharing"

  - id: metal_earth
    name: Metal Earth
    sheet_id: 1Gwe3_D7n7qaRIAGVJ0QZgsaaZiuQUL1Y4SXtP--f4uU
    link: "https://docs.google.com/spreadsheets/d/1Gwe3_D7n7qaRIAGVJ0QZgsaaZiuQUL1Y4SXtP--f4uU/edit?usp=sharing"

  - id: winning_moves
    name: Winning Moves
    sheet_id: 1Xypdo82ug3HJi61bSuP6k1UJ3tBvZLKGab7Lf3PC7s4
    link: "https://docs.google.com/spreadsheets/d/1Xypdo82ug3HJi61bSuP6k1UJ3tBvZLKGab7Lf3PC7s4/edit?usp=sharing"

  - id: moore
    name: Moore
    sheet_id: 1XkOEoCVd6PtbqxNxIMcgppskB9MwHXBkKbocgRoZK3Q
    link: "https://docs.google.com/spreadsheets/d/1XkOEoCVd6PtbqxNxIMcgppskB9MwHXBkKbocgRoZK3Q/edit?usp=sharing"

  - id: sands
    name: Sands
    sheet_id: 1tG-FDZNW-Mbyp0uQU1oR_nMiahKHpMEv2p8wYKgo5uM
    link: "https://docs.google.com/spreadsheets/d/1tG-FDZNW-Mbyp0uQU1oR_nMiahKHpMEv2p8wYKgo5uM/edit?usp=sharing"

  - id: playkidiz
    name: Playkidiz
    sheet_id: 1kROK5Pn5JsIU0fsi1Jj1JJrZKIazsb5MiicITAyVX6c
    link: "https://docs.google.com/spreadsheets/d/1kROK5Pn5JsIU0fsi1Jj1JJrZKIazsb5MiicITAyVX6c/edit?usp=sharing"

  - id: kent
    name: Kent
    sheet_id: 1p9Vx569XOxoTDWUqShl3m5eSRmwIKTru
    link: "https://docs.google.com/spreadsheets/d/1p9Vx569XOxoTDWUqShl3m5eSRmwIKTru/edit?usp=sharing"

  - id: gi_go
    name: Gi-Go
    sheet_id: 1i18-ZOtmEqDP9_coQWkK9uD1Gg-0zTLMivzdCQfHDj8
    link: "https://docs.google.com/spreadsheets/d/1i18-ZOtmEqDP9_coQWkK9uD1Gg-0zTLMivzdCQfHDj8/edit?usp=sharing"

  - id: goplay
    name: Goplay
    sheet_id: 1sZwpjm4ItQh2KCYxyBroshLdI5HJ_iFFwvilmBuFkjw
    link: "https://docs.google.com/spreadsheets/d/1sZwpjm4ItQh2KCYxyBroshLdI5HJ_iFFwvilmBuFkjw/edit?usp=sharing"

  - id: rhode_island
    name: Rhode Island
    sheet_id: 1Wv6olci3_gta46gyBbI5UEFN0kWaoW7SXi5TNYz1V1Y
    link: "https://docs.google.com/spreadsheets/d/1Wv6olci3_gta46gyBbI5UEFN0kWaoW7SXi5TNYz1V1Y/edit?usp=sharing"

  - id: colours_craft
    name: Colours Craft
    sheet_id: 1T3fnUzr8nS8H5ssCn-G1TILdpd0Opy0KrUHK5PEXKuc
    link: "https://docs.google.com/spreadsheets/d/1T3fnUzr8nS8H5ssCn-G1TILdpd0Opy0KrUHK5PEXKuc/edit?usp=sharing"

  - id: atiko
    name: Atiko
    sheet_id: 1B4lKooxcy906f938o2ZHg5tXQkvAyDJ18EqIqad3diM
    link: "https://docs.google.com/spreadsheets/d/1B4lKooxcy906f938o2ZHg5tXQkvAyDJ18EqIqad3diM/edit?usp=sharing"

  - id: play_dough
    name: Play Dough
    sheet_id: 11EDkcZZsXyNETYAzMd-EYSk0kd-sHjwvJCrINOP8zaM
    link: "https://docs.google.com/spreadsheets/d/11EDkcZZsXyNETYAzMd-EYSk0kd-sHjwvJCrINOP8zaM/edit?usp=sharing"

  - id: microkick
    name: Microkick
    sheet_id: 1rKHgC5T8zCLzLB2s7KBIudjem_MbHVqNMK1bYE8-ki8
    link: "https://docs.google.com/spreadsheets/d/1rKHgC5T8zCLzLB2s7KBIudjem_MbHVqNMK1bYE8-ki8/edit?usp=sharing"

  - id: lchaim
    name: Lchaim
    sheet_id: 1nxVzi3RN5STkbwT4cD0OyqaTehMHChtssDgEiYcH0Nk
    link: "https://docs.google.com/spreadsheets/d/1nxVzi3RN5STkbwT4cD0OyqaTehMHChtssDgEiYcH0Nk/edit?usp=sharing"

  - id: samvix
    name: Samvix
    sheet_id: 1f3xjT_n_hS7Wpp5LgryuxEZTBehnCLeyRdE1lR70eXo
    link: "https://docs.google.com/spreadsheets/d/1f3xjT_n_hS7Wpp5LgryuxEZTBehnCLeyRdE1lR70eXo/edit?usp=sharing"

  - id: chazak
    name: Chazak
    sheet_id: 1Iv74C8jS-ST9246hTOh9df6FkxnygazTX91H6FIDRw4
    link: "https://docs.google.com/spreadsheets/d/1Iv74C8jS-ST9246hTOh9df6FkxnygazTX91H6FIDRw4/edit?usp=sharing"
